accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts' 
urlpatterns = [
    path('', views.index, name="index"),
    path('<int:pk>/profile/', views.detail, name="detail"),
    path('create/', views.create, name="create"),
    path('<int:pk>/update/', views.update, name="update"),
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

list/urls.py
from django.urls import path
from . import views

app_name = 'list'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('others_list/', views.others_list, name='others_list'),
    path('<int:pk>/detail/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/create_comment/', views.create_comment, name='create_comment'),
    path('<int:id>/delete_comment/<int:pk>', views.delete_comment, name='delete_comment'),
    path('<int:pk>/status_update/', views.status_update, name='status_update'),
    path('share_open/', views.share_open, name='share_open'),
    path('share_close/', views.share_close, name='share_close'),
    path('googlef0f289258061b898.html', views.GoogleSearchConsoleView.as_view(), name='GoogleSearchConsole'),
]

listapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('list.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill
from django.core.validators import MaxLengthValidator
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    class Meta:
        db_table = 'profile'

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    ## ハンドルネーム
    name = models.CharField(max_length=50, blank=True)

    ## 1:Mailaddress、2:Twitter、3:Facebook
    social_flag = models.IntegerField(default=1)

    ## イメージ画像
    profile_image = models.ImageField(
        upload_to='uploads/%Y/%m/%d/',
        blank=True
    )
    
    profile_image_edit = ImageSpecField(
        source='profile_image',
        processors=[ResizeToFill(150, 150)],
        format='JPEG'
    )

    ## プロフィール説明
    profile_content = models.TextField(validators=[MaxLengthValidator(200)], blank=True)

    ## Twitter
    twitter = models.CharField(max_length=50, blank=True)


    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)


    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()


    def __str__(self):
        return self.name

accounts/forms.py
from django import forms
from django.forms import ModelForm
from .models import Profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('name', 'profile_image', 'profile_content', 'twitter')

    name = forms.TextInput(attrs={'size': 40})
    profile_image = forms.ImageField(required = False)
    profile_content = forms.Textarea(attrs={'cols': 20, 'rows': 2})
    twitter = forms.CharField(required=False)

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from .models import Profile
from .forms import ProfileForm


@login_required
def index(request):
    profile = Profile.objects.filter(user_id=request.user.id)
    if profile.exists():
        return render(request, 'accounts/index.html', {'profile':profile[0]})
    else:
        form = ProfileForm()
        return render(request, 'accounts/create_profile.html', {'form':form})


def detail(request, pk):
    profile = get_object_or_404(Profile, id=pk)
    return render(request, 'accounts/detail.html', {'profile':profile})


@login_required
def create(request):
    form = ProfileForm(request.POST, request.FILES)
    if form.is_valid():
        profile = form.save(commit=False)
        profile.user_id = request.user.id
        profile.save()
    return redirect('list:index')


@login_required
def update(request, pk):
    profile = get_object_or_404(Profile, id=pk)
    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            profile.name = form.cleaned_data['name']
            profile.profile_image = form.cleaned_data['profile_image']
            profile.profile_content = form.cleaned_data['profile_content']
            profile.twitter = form.cleaned_data['twitter']
            profile.save()
            return redirect('accounts:index')
    else:
        form = ProfileForm(
            initial={
                'name':profile.name,
                'profile_image':profile.profile_image,
                'profile_content':profile.profile_content,
                'twitter':profile.twitter,
            }
        )
    return render(request, 'accounts/update.html', {'form':form, 'pk':pk })   


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

templates/accounts/create_profile.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load staticfiles %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-7 col-sm-10 col-xs-10" id="banner">
                <h3>Update Your Profile</h3>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-2 col-md-1 col-sm-1 col-xs-1">
        </div>
        <div class="col-lg-8 col-md-10 col-sm-10 col-xs-10">
            <form class="form-horizontal" action="{% url 'accounts:create' %}" method="POST" enctype="multipart/form-data" autocomplete="off">
                {% csrf_token %}
                {% for field, errors in form.errors.items %}
                    {% for error in errors %}
                        <p class="alert alert-danger">{{ error }}</p>
                    {% endfor %}
                {% endfor %}
                <div class="form-group">
                    <label class="col-sm-2 control-label">{{ form.name.label_tag }}</label>
                    <div class="col-sm-8">{{form.name|add_class:"form-control"}}</div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">{{ form.profile_content.label_tag }}</label>
                    <div class="col-sm-8">{{form.profile_content|add_class:"form-control"}}</div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">{{ form.profile_image.label_tag }}</label>
                    <div class="col-sm-8">{{form.profile_image|add_class:"form-control"}}</div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">{{ form.twitter.label_tag }}</label>
                    <div class="col-sm-8">{{form.twitter|add_class:"form-control"}}</div>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-right">送信</button>
                    <a href="{% url 'accounts:index' %}" class="btn btn-secondary btn-right">戻る</a>
                </div>
            </form>
        </div>
        <div class="col-lg-2 col-md-1 col-sm-1 col-xs-1">
        </div>
    </div>
</div>

{% endblock %}

templates/accounts/detail.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load staticfiles %}
{% block content %}

<div class="container profile_box">
    <div class="row">
        <div class="col-lg-3 col-md-3 col-sm-2 col-xs-2">
        </div>
        <div class="col-lg-6 col-md-6 col-sm-8 col-xs-8">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="profile_img">
                        {% if profile.profile_image %}
                            <p><img src="{{ profile.profile_image_edit.url }}" class="image-round1"></p>
                        {% else %}
                            <p><i class="far fa-user-circle fa-5x awe_profile_img"></i></p><br>
                            <p>No Profile Image</p>
                        {% endif %}
                        {% if profile.name %}
                            <h3>{{ profile.name }}</h3>
                        {% else %}
                            <p>No Hundle Name</p>
                        {% endif %}
                    </div>
                    <div>
                        {% if profile.profile_content %}
                            <p>{{ profile.profile_content }}</p>
                        {% else %}
                            <p>No Profile</p>
                        {% endif %}
                    </div>
                    <hr>
                    <div>
                        {% if profile.twitter %}
                            <p><i class="fab fa-twitter-square awe_cust fa-2x"></i> <a href={{ profile.twitter }} target="_blank">{{ profile.twitter }}</a></p>
                        {% else %}
                            <p><i class="fab fa-twitter-square awe_cust fa-2x"></i> No Twitter ID</p>
                        {% endif %}
                    </div>
                    <BR>
                    <div class="button_area">
                    {% if user.id == profile.user_id %}
                        <a href="{% url 'accounts:update' pk=profile.id %}" class="btn btn-primary btn-right">編集</a>
                        <a href="{% url 'list:index' %}" class="btn btn-secondary btn-right">戻る</a>
                    {% else %}
                        <a href="{% url 'list:others_list' %}" class="btn btn-secondary btn-right">戻る</a>
                    {% endif %}
                    </div>
                    <HR>
                    {% if user.id == profile.user_id %}
                        <div class="">
                            <p>Listの公開設定を一括変更する</p>
                            <a href="{% url 'list:share_open' %}" class="btn btn-primary btn-right">公開</a>
                            <a href="{% url 'list:share_close' %}" class="btn btn-danger btn-right">非公開</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-2 col-xs-2">
        </div>
    </div>
</div>

{% endblock %}

templates/accounts/index.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}

<div class="container profile_box">
    <div class="row">
        <div class="col-lg-3 col-md-3 col-sm-2 col-xs-2">
        </div>
        <div class="col-lg-6 col-md-6 col-sm-8 col-xs-8">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="profile_img">
                        {% if profile.profile_image %}
                            <p><img src="{{ profile.profile_image_edit.url }}" class="image-round1"></p>
                        {% else %}
                            <p><i class="far fa-user-circle fa-5x awe_profile_img"></i></p><br>
                            <p>No Profile Image</p>
                        {% endif %}
                        {% if profile.name %}
                            <h3>{{ profile.name }}</h3>
                        {% else %}
                            <p>No Hundle Name</p>
                        {% endif %}
                        {% if profile.profile_content %}
                            <p>{{ profile.profile_content }}</p>
                        {% else %}
                            <p>No Profile</p>
                        {% endif %}
                    </div>
                    <hr>
                    <div class="profile_social">
                        {% if profile.twitter %}
                            <p><i class="fab fa-twitter-square awe_cust fa-2x"></i> <a href={{ profile.twitter }} target="_blank">{{ profile.twitter }}</a></p>
                        {% else %}
                            <p><i class="fab fa-twitter-square awe_cust fa-2x"></i> No Twitter ID</p>
                        {% endif %}
                    </div>
                    <BR>
                    <div class="button_area">
                    {% if user.id == profile.user_id %}
                        <a href="{% url 'accounts:update' pk=profile.id %}" class="btn btn-primary btn-right">編集</a>
                        <a href="{% url 'list:index' %}" class="btn btn-secondary btn-right">戻る</a>
                    {% else %}
                        <a href="{% url 'list:others_list' %}" class="btn btn-secondary btn-right">戻る</a>
                    {% endif %}
                    </div>
                    <HR>
                    {% if user.id == profile.user_id %}
                        <div class="">
                            <p>Listの公開設定を一括変更する</p>
                            <a href="{% url 'list:share_open' %}" class="btn btn-primary btn-right">公開</a>
                            <a href="{% url 'list:share_close' %}" class="btn btn-danger btn-right">非公開</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-2 col-xs-2">
        </div>
    </div>
</div>

{% endblock %}

templates/accounts/signup.html
{% load widget_tweaks %}
{% load static %}
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<!-- bootstrap -->
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
<!-- base -->
<link rel="stylesheet" href="{% static 'css/base.css' %}" />
<link rel="stylesheet" href="{% static 'css/list.css' %}" />
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
{% block content %}

<div class="container">
    <div class="row">
        <h4>（仮）100Lists</h4>
    </div>
    <HR>
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <h3>ユーザー登録</h3>
            <div class="box">
                <form method="post" autocomplete="off" class="login-container">
                    {% csrf_token %}
                    {% for field, errors in form.errors.items %}
                        {% for error in errors %}
                            <p class="alert alert-danger">{{ error }}</p>
                        {% endfor %}
                    {% endfor %}
                    <div class="divider-form"></div>

                    <div class="form-group">
                        <label for="exampleInputEmail1">User Name</label>
                        {{ form.username|add_class:"form-control" }}
                        <p class="small_text">半角アルファベット、半角数字、@/./+/-/_ で150文字以下にしてください。</p>
                    </div>

                    <div class="divider-form"></div>

                    <div class="form-group">
                        <label for="exampleInputPassword1">Password</label>
                        {{ form.password1|add_class:"form-control" }}
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Password(Re)</label>
                        {{ form.password2|add_class:"form-control" }}
                        <p class="small_text">・あなたの他の個人情報と似ているパスワードにはできません。</p>
                        <p class="small_text">・パスワードは最低 8 文字以上必要です。</p>
                        <p class="small_text">・よく使われるパスワードにはできません。</p>
                        <p class="small_text">・数字だけのパスワードにはできません。</p>
                    </div>

                    <div class="divider-form"></div>
                    <button type="submit" class="btn-block btn btn-lg btn-primary">Sign up</button>

                    <p class="text-center">アカウントがある方は<a href="{% url 'login' %}">コチラ</a>でログイン</p>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/accounts/update.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load staticfiles %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-7 col-sm-10 col-xs-10" id="banner">
                <h3>Update Your Profile</h3>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-2 col-md-1 col-sm-1 col-xs-1">
        </div>
        <div class="col-lg-8 col-md-10 col-sm-10 col-xs-10">
            <form class="form-horizontal" action="{% url 'accounts:update' pk=pk %}" method="POST" enctype="multipart/form-data" autocomplete="off">
                {% csrf_token %}
                {% for field, errors in form.errors.items %}
                    {% for error in errors %}
                        <p class="alert alert-danger">{{ error }}</p>
                    {% endfor %}
                {% endfor %}
                <div class="form-group">
                    <label class="col-sm-2 control-label">{{ form.name.label_tag }}</label>
                    <div class="col-sm-8">{{form.name|add_class:"form-control"}}</div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">{{ form.profile_content.label_tag }}</label>
                    <div class="col-sm-8">{{form.profile_content|add_class:"form-control"}}</div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">{{ form.profile_image.label_tag }}</label>
                    <div class="col-sm-8">
                    {{form.profile_image|add_class:"form-control"}}
                    <p class="small_text">※変更後の画像ファイルが指定されていない場合、削除になります。</p>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">{{ form.twitter.label_tag }}</label>
                    <div class="col-sm-8">{{form.twitter|add_class:"form-control"}}</div>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-right">送信</button>
                    <a href="{% url 'accounts:index' %}" class="btn btn-secondary btn-right">戻る</a>
                </div>
            </form>
        </div>
        <div class="col-lg-2 col-md-1 col-sm-1 col-xs-1">
        </div>
    </div>
</div>

{% endblock %}