accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts' 
urlpatterns = [
    path('', views.index, name="index"),
    path('<int:pk>/profile/', views.detail, name="detail"),
    path('create/', views.create, name="create"),
    path('<int:pk>/update/', views.update, name="update"),
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

list/urls.py
from django.urls import path
from . import views

app_name = 'list'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('others_list/', views.others_list, name='others_list'),
    path('<int:pk>/detail/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/create_comment/', views.create_comment, name='create_comment'),
    path('<int:id>/delete_comment/<int:pk>', views.delete_comment, name='delete_comment'),
    path('<int:pk>/status_update/', views.status_update, name='status_update'),
    path('share_open/', views.share_open, name='share_open'),
    path('share_close/', views.share_close, name='share_close'),
    path('googlef0f289258061b898.html', views.GoogleSearchConsoleView.as_view(), name='GoogleSearchConsole'),
]

listapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('list.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

list/forms.py
from django import forms
from django.forms import ModelForm
from .models import List, Comment


class ListForm(forms.ModelForm):
    class Meta:
        model = List
        fields = ('title', 'content', 'due_date', 'rank', 'image', 'share')

    '''
    def __init__(self, *args, **kwargs):
        super(ListForm, self).__init__(*args, **kwargs)
        self.fields['origin'].widget.attrs = {'id':'selectedFile'} 
    '''
    choice_list_rank = (
        (1, u'A（最優先でやる）'),
        (2, u'B（そのうちやる）'),
        (3, u'C（いつかやる）'),
    )

    choice_list_share = (
        (1, u'公開する'),
        (2, u'公開しない'),
    )

    title = forms.TextInput(attrs={'placeholder': 'Enter description here', 'size': 40})
    content = forms.Textarea(attrs={'cols': 20, 'rows': 2})
    due_date = forms.DateTimeField(required=False)
    rank = forms.ChoiceField(choices=choice_list_rank, initial=1)
    image = forms.ImageField(required = False)
    share = forms.ChoiceField(choices=choice_list_share, initial=2)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)

    comment = forms.Textarea(),

templates/base.html
{% load static %}

<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="あなたの100のリストをいつでも手の中に。夢の実現を加速させるツール。">
    <title>(仮)100Lists</title>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <!-- bootstrap -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <!-- base -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" href="{% static 'css/list.css' %}" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
</head>

<body>
    <header>
        <div class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <a href="/" class="navbar-brand">(仮)100lists</a>
                    <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse" id="navbar-main">
                    <ul class="nav navbar-nav">
                        {% if user.is_authenticated %}
                        <li><a href="/">Your Lists</a></li>
                        {% endif %}
                        <li><a href="/others_list/">Other's Lists</a></li>
                        {% if user.is_authenticated %}
                        <li><a href="/accounts/">Profile</a></li>
                        <li><a href="{% url 'logout' %}" class="logout">Logout</a></li>
                        {% else %}
                        <li><a href="{% url 'accounts:signup' %}" class="signup">Sign up</a></li>
                        <li><a href="{% url 'login' %}" class="login">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </header>
    {% block content %}
    {% endblock %}
</div>
    
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous">
        
</script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
<script>
    $(function () {
        let dateFormat = 'yy-mm-dd';
        $('#id_due_date').datepicker({
            dateFormat: dateFormat
        });
    });
</script>
</body>
</html>