accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts' 
urlpatterns = [
    path('', views.index, name="index"),
    path('<int:pk>/profile/', views.detail, name="detail"),
    path('create/', views.create, name="create"),
    path('<int:pk>/update/', views.update, name="update"),
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

list/urls.py
from django.urls import path
from . import views

app_name = 'list'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('others_list/', views.others_list, name='others_list'),
    path('<int:pk>/detail/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/create_comment/', views.create_comment, name='create_comment'),
    path('<int:id>/delete_comment/<int:pk>', views.delete_comment, name='delete_comment'),
    path('<int:pk>/status_update/', views.status_update, name='status_update'),
    path('share_open/', views.share_open, name='share_open'),
    path('share_close/', views.share_close, name='share_close'),
    path('googlef0f289258061b898.html', views.GoogleSearchConsoleView.as_view(), name='GoogleSearchConsole'),
]

listapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('list.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

list/models.py
from django.db import models
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill

from django.contrib.auth.models import User


class List(models.Model):
    class Meta:
        db_table = 'list'

    ## 名称
    title = models.CharField(max_length=50)

    ## 内容
    content = models.TextField()

    ## 期日
    due_date = models.DateField(blank=True, null=True)

    ## カテゴリー
    ## 今後実装
    #category = models.IntegerField(default=0)

    ## ランク（重要度）
    ## 1:A（すぐにやる）、2:B（そのうちやる）、3:C（いつかやる）
    rank = models.IntegerField(default=0)

    ## 登録日
    created_at = models.DateTimeField(auto_now_add=True)

    ## Userテーブルとのリレーション
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    ## イメージ画像
    image = models.ImageField(
        upload_to='uploads/%Y/%m/%d/',
        blank=True
    )
    
    image_edit = ImageSpecField(
        source="image",
        processors=[ResizeToFill(560, 250)],
        format='JPEG'
    )

    ## 達成ステータス（True：達成済み、False：実行中）
    status = models.BooleanField(default=False)

    ## 公開ステータス
    ## 1:公開する、2:公開しない
    share = models.IntegerField(default=2)

    def __str__(self):
        return self.title


class Comment(models.Model):
    class Meta:
        db_table = 'comment'

    ## コメント
    comment = models.TextField(max_length=100)

    ## 登録日
    created_at = models.DateTimeField(auto_now_add=True)


    ## listテーブルとのリレーション
    list = models.ForeignKey(List, on_delete=models.CASCADE)

list/forms.py
from django import forms
from django.forms import ModelForm
from .models import List, Comment


class ListForm(forms.ModelForm):
    class Meta:
        model = List
        fields = ('title', 'content', 'due_date', 'rank', 'image', 'share')

    '''
    def __init__(self, *args, **kwargs):
        super(ListForm, self).__init__(*args, **kwargs)
        self.fields['origin'].widget.attrs = {'id':'selectedFile'} 
    '''
    choice_list_rank = (
        (1, u'A（最優先でやる）'),
        (2, u'B（そのうちやる）'),
        (3, u'C（いつかやる）'),
    )

    choice_list_share = (
        (1, u'公開する'),
        (2, u'公開しない'),
    )

    title = forms.TextInput(attrs={'placeholder': 'Enter description here', 'size': 40})
    content = forms.Textarea(attrs={'cols': 20, 'rows': 2})
    due_date = forms.DateTimeField(required=False)
    rank = forms.ChoiceField(choices=choice_list_rank, initial=1)
    image = forms.ImageField(required = False)
    share = forms.ChoiceField(choices=choice_list_share, initial=2)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)

    comment = forms.Textarea(),

list/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from .forms import ListForm, CommentForm
from .models import List, Comment


@login_required
def index(request):
    user_lists = List.objects.filter(user__id=request.user.id).order_by('-created_at')
    return render(request, 'list/index.html', {'user_lists':user_lists})
 
 
def detail(request, pk):
    list_val = List.objects.get(id=pk)
    comment_val = Comment.objects.filter(list_id=pk)
    form = CommentForm()
    return render(request, 'list/detail.html', {'list_val':list_val, 'comment_val':comment_val, 'form':form })


@login_required
def create(request):
    if request.method == "POST":
        form = ListForm(request.POST, request.FILES)
        if form.is_valid():
            List = form.save(commit=False)
            List.user_id = request.user.id
            List.save()
            return redirect('list:index')
    else:
        form = ListForm()
    return render(request, 'list/create.html', {'form':form})
 

@login_required
def update(request, pk):
    list = get_object_or_404(List, id=pk)

    if request.method == "POST":
        form = ListForm(request.POST, request.FILES)
        if form.is_valid():
            list.title = form.cleaned_data['title']
            list.content = form.cleaned_data['content']
            list.due_date = form.cleaned_data['due_date']
            list.rank = form.cleaned_data['rank']
            list.share = form.cleaned_data['share']
            list.image = form.cleaned_data['image']
            list.save()
            return redirect('list:detail', pk=pk)
    else:
        form = ListForm(
            initial={
                'title':list.title,
                'content':list.content,
                'due_date':list.due_date,
                'rank':list.rank,
                'share':list.share,
                'image':list.image
            }
        )
    return render(request, 'list/update.html', {'form':form, 'pk':pk, 'image_edit':list.image_edit})   


@login_required
def delete(request, pk):
    List.objects.get(pk=pk).delete()
    return redirect('list:index')


@login_required
def create_comment(request, pk):
    form = CommentForm(request.POST)
    if form.is_valid():
        Comment = form.save(commit=False)
        Comment.list_id = pk
        Comment.save()
    return redirect('list:detail', pk=pk)


@login_required
def delete_comment(request, pk, id):
    Comment.objects.get(pk=pk).delete()
    return redirect('list:detail', pk=id)


@login_required
def status_update(request, pk):
    list = get_object_or_404(List, id=pk)
    if list.status == False:
        list.status = True
    else:
        list.status = False
    list.save()
    return redirect('list:index')


def others_list(request):
    lists = List.objects.filter(share=1).exclude(user_id=request.user.id).order_by('created_at')[:20]
    return render(request, 'list/others.html', {'lists':lists})


@login_required
def share_open(request):
    user_lists = List.objects.filter(user__id=request.user.id)
    for v in user_lists:
        v.share = 1
        v.save()
    return redirect('accounts:index')


@login_required
def share_close(request):
    user_lists = List.objects.filter(user__id=request.user.id)
    for v in user_lists:
        v.share = 2
        v.save()
    return redirect('accounts:index')


class GoogleSearchConsoleView(TemplateView):
    template_name = 'googlef0f289258061b898.html'

templates/list/create.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}


<div class="container">
    <div class="content">
        <div class="row">
            <div class="col-lg-8 col-md-7 col-sm-10 col-xs-10" id="banner">
                <h3>New</h3>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-2 col-md-1 col-sm-1 col-xs-1">
            </div>
            <div class="col-lg-8 col-md-10 col-sm-10 col-xs-10">
                <div class="well bs-component">
                    <form class="form-horizontal" action="{% url 'list:create' %}" method="POST" enctype="multipart/form-data" autocomplete="off">
                        {% csrf_token %}
                        {% for field, errors in form.errors.items %}
                            {% for error in errors %}
                                <p class="alert alert-danger">{{ error }}</p>
                            {% endfor %}
                        {% endfor %}
                        <div class="form-group">
                            <label class="col-sm-2 control-label">{{ form.title.label_tag }}</label>
                            <div class="col-sm-8">{{form.title|add_class:"form-control"}}</div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">{{ form.content.label_tag }}</label>
                            <div class="col-sm-8" id="textarea_size">{{form.content|add_class:"textarea_size form-control"}}</div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-2 col-md-2 col-sm-2 col-xs-10 control-label">{{ form.due_date.label_tag }}</label>
                            <div class="col-lg-4 col-md-6 col-sm-6 col-xs-8">{{form.due_date|add_class:"form-control"}}</div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-2 col-md-2 col-sm-2 col-xs-10 control-label">{{ form.rank.label_tag }}</label>
                            <div class="col-lg-4 col-md-6 col-sm-6 col-xs-8">{{form.rank|add_class:"form-control"}}</div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-2 col-md-2 col-sm-2 col-xs-10 control-label">{{ form.share.label_tag }}</label>
                            <div class="col-lg-4 col-md-6 col-sm-6 col-xs-8">{{form.share|add_class:"form-control"}}</div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-2 col-md-2 col-sm-2 col-xs-2 control-label">{{ form.image.label_tag }}</label>
                            <div class="col-lg-8 col-md-10 col-sm-10 col-xs-10">{{form.image|add_class:"form-control"}}</div>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-right">送信</button>
                            <a href="{% url 'list:index' %}" class="btn btn-secondary btn-right">戻る</a>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-lg-2 col-md-1 col-sm-1 col-xs-1">
            </div>
        </div>
    </div>
</div>
                            

{% endblock %}

templates/list/detail.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}

<div class="container">
    <div class="content">
        <div class="row">
            <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10" id="banner">
                <h3>
                    {% if user.id == list_val.user_id %}
                        {% if list_val.status == True %}
                            <i class="fas fa-crown awe_crown"></i>{{ list_val.title }}
                            <a href="{% url 'list:status_update' pk=list_val.id %}" class="btn btn-danger btn-right">実行中にする</a>
                        {% else %}
                            {{ list_val.title }}
                            <a href="{% url 'list:status_update' pk=list_val.id %}" class="btn btn-primary btn-right">達成済にする</a>
                        {% endif %}
                    {% else %}
                        {{ list_val.title }}
                    {% endif %}
                </h3>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-3 col-md-2 col-sm-1 col-xs-1">
            </div>
            <div class="col-lg-6 col-md-7 col-sm-9 col-xs-9">
                {% if not list_val.image %}
                
                {% else %}
                    <img src="{{ list_val.image_edit.url }}" class="img-responsive">
                {% endif %}
                
                <div class="panel panel-default">
                    <div class="panel-body">
                        <p class="lead">
                            Content:
                        </p>
                        <p>{{ list_val.content }}</p><hr>
                        <p><a href="{% url 'accounts:detail' pk=list_val.user.profile.id %}">User : {{ list_val.user.profile.name }}</a></p>
                        <p>Due Date : {{ list_val.due_date }}</p>
                        {% if list_val.rank == 1 %}
                            <p>Rank : A（最優先でやる）</p>
                        {% elif list_val.rank == 2 %}
                            <p>Rank : B（そのうちやる）</p>
                        {% else %}
                            <p>Rank : C（いつかやる）</p>
                        {% endif %}
                        {% if list_val.share == 1 %}
                            <p>Share : 公開する</p>
                        {% else %}
                            <p>Share : 公開しない</p>
                        {% endif %}
                        <p> created at : {{ list_val.created_at }}</p>
                        {% if user.id == list_val.user_id %}
                            <a href="{% url 'list:update' pk=list_val.id %}" class="btn btn-primary btn-right">編集</a>
                            <a href="{% url 'list:delete' pk=list_val.id %}" class="btn btn-danger btn-right" onclick='return confirm("削除してよろしいですか？");'>削除</a>
                            <a href="{% url 'list:index' %}" class="btn btn-secondary btn-right">戻る</a>
                        {% else %}
                            <a href="{% url 'list:others_list' %}" class="btn btn-secondary btn-right">戻る</a>
                        {% endif %}
                    </div>
                </div>
                
                {% for v in comment_val %}
                    <div class="box26">
                        <span class="box-title">
                            {{ v.created_at }}
                            {% if user.id == list_val.user_id %}
                                <a href="{% url 'list:delete_comment' pk=v.id id=list_val.id%}" class="btn btn-danger btn-xs" onclick='return confirm("削除してよろしいですか？");'>削除</a>
                            {% endif %}
                            </span>
                        <p>{{ v.comment }}</p>
                    </div>
                {% empty %}
                    <p>コメントはありません</p>
                {% endfor %}

                {% if user.id == list_val.user_id %}
                    <form class="form-horizontal" action="{% url 'list:create_comment' pk=list_val.id %}" method="POST" autocomplete="off">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="col-lg-2 col-md-2 col-sm-2 col-xs-2 control-label">{{ form.comment.label_tag }}</label>
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id="comment_textarea_size">{{form.comment|add_class:"form-control"}}<p class="small_text">※自分のみ投稿できます。</p></div>

                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-right">投稿</button>
                        </div>
                    </form>
                {% else %}
                    
                {% endif %}           
            </div>
            <div class="col-lg-3 col-md-2 col-sm-1 col-xs-1">
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/list/index.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container">
    <div class="content">

        <div class="row">
            <div class="col-lg-8 col-md-7 col-sm-6 col-xs-6" id="banner">
                <h3>Your Lists</h3>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4 col-md-5 col-sm-6 col-xs-6">
                <a href="{% url 'list:create' %}">
                    <i class="fas fa-plus-circle fa-2x awe_cust"></i>
                </a>
            </div>
        </div>
        <div class="row">
            {% for v in user_lists %}
                <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12 list_heading2">
                    <a href="{% url 'list:detail' pk=v.id %}">
                        {% if v.status == True %}
                            <i class="fas fa-crown awe_crown"></i>{{ v.title }}<div class="hidden-sm hidden-xs list_created_at">登録日：{{ v.created_at }}</div>
                        {% else %}
                            {{ v.title }}<div class="hidden-sm hidden-xs list_created_at">登録日：{{ v.created_at }}</div>
                        {% endif %}
                    </a>
                </div>
            {% empty %}
                <p>まだ、リストが登録されていません。最初のリストを登録して見ましょう！</p>
            {% endfor %}
            
        </div>
        
    </div>
</div>

{% endblock %}

templates/list/others.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container">
    <div class="content">

        <div class="row">
            <div class="col-lg-8 col-md-7 col-sm-6 col-xs-6" id="banner">
                <h3>Other's Lists</h3>
                <p class="small_text">※公開設定された投稿のみ表示されます。</p></div>
            </div>
        </div>

        <div class="row">
            {% for v in lists %}
                <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12 list_heading3">
                    <a href="{% url 'list:detail' pk=v.id %}">
                        {{ v.title }}<div class="hidden-sm hidden-xs list_created_at">登録ユーザー：{{ v.user.profile.name }}</div>
                    </a>
                </div>
            {% empty %}
                <p>リストが登録されていません</p>
            {% endfor %}
            
        </div>

    </div>
</div>

{% endblock %}

templates/list/update.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load imagekit %}
{% block content %}

<div class="container">
    <div class="content">

        <div class="row">
            <div class="col-lg-8 col-md-7 col-sm-6" id="banner">
                <h3>Update</h3>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-2 col-md-1 col-sm-1 col-xs-1">
            </div>
            <div class="col-lg-8 col-md-10 col-sm-10 col-xs-10">
                <div class="well bs-component">
                    <form class="form-horizontal" action="{% url 'list:update' pk=pk %}" method="POST" enctype="multipart/form-data" autocomplete="off">
                        {% csrf_token %}
                        {% for field, errors in form.errors.items %}
                            {% for error in errors %}
                                <p class="alert alert-danger">{{ error }}</p>
                            {% endfor %}
                        {% endfor %}
                        <div class="form-group">
                            <label class="col-sm-2 control-label">{{ form.title.label_tag }}</label>
                            <div class="col-sm-8">{{ form.title|add_class:"form-control" }}</div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">{{ form.content.label_tag }}</label>
                            <div class="col-sm-8" id="textarea_size">{{ form.content|add_class:"textarea_size form-control" }}</div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-2 col-md-2 col-sm-2 col-xs-10 control-label">{{ form.due_date.label_tag }}</label>
                            <div class="col-lg-4 col-md-6 col-sm-6 col-xs-8">{{ form.due_date|add_class:"form-control" }}</div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-2 col-md-2 col-sm-2 col-xs-10 control-label">{{ form.rank.label_tag }}</label>
                            <div class="col-lg-4 col-md-6 col-sm-6 col-xs-8">{{ form.rank|add_class:"form-control" }}</div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-2 col-md-2 col-sm-2 col-xs-10 control-label">{{ form.share.label_tag }}</label>
                            <div class="col-lg-4 col-md-6 col-sm-6 col-xs-8">{{ form.share|add_class:"form-control" }}</div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-2 col-md-2 col-sm-2 col-xs-2 control-label">{{ form.image.label_tag }}</label>
                            <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10">
                                {{ form.image|add_class:"form-control" }}
                                <p class="small_text">※変更後の画像ファイルが指定されていない場合、削除になります。</p>
                            </div>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-right">送信</button>
                            <a href="{% url 'list:detail' pk=pk %}" class="btn btn-secondary btn-right">戻る</a>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-lg-2 col-md-1 col-sm-1 col-xs-1">
            </div>
        </div>
    </div>
</div>


{% endblock %}